[package]
name = "nano-nn"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.39"
eframe = "0.31.1"
image = "0.25.6"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
